spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://localhost:10000
          predicates:
            - Path=/auth/*

        - id: surveyresult-server
          uri: http://localhost:30000
          predicates:
            - Path=/surveys/*/results

        - id: survey-service
          uri: http://localhost:20000
          predicates:
            - Path=/surveys*/**

