spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: http://${MEMBER_SERVICE_ADDR}:${MEMBER_SERVICE_PORT}
          predicates:
            - Path=/api/auth/*
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: survey-result-service
          uri: http://${SURVEY_RESULT_SERVICE_ADDR}:${SURVEY_RESULT_SERVICE_PORT}
          predicates:
            - Path=/api/surveys/*/results
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: survey-service
          uri: http://${SURVEY_SERVICE_ADDR}:${SURVEY_SERVICE_PORT}
          predicates:
            - Path=/api/surveys*/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

