apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: syua0529/apigateway
          env:
            - name: MEMBER_SERVICE_ADDR
              value: "memberserver-service.member-service.svc.cluster.local"
            - name: MEMBER_SERVICE_PORT
              value: "8080"
            - name: SURVEY_SERVICE_ADDR
              value: "surveyserver-service.survey-service.svc.cluster.local"
            - name: SURVEY_SERVICE_PORT
              value: "8080"
            - name: SURVEY_RESULT_SERVICE_ADDR
              value: "surveyserver-result-service.survey-result-service.svc.cluster.local"
            - name: SURVEY_RESULT_SERVICE_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
